### ISSUE TITLE
Isolate TPS3705 reset signal

### ISSUE THREAD

**Issue by prasimix** [eez-open/psu-hw#14]
Arduino IDE cannot reset the board when firmware is uploaded and reset has to be applied after uploading attempt. The reason for that is that TPS3705 is holding RESET line high (inactive). That makes a whole uploading procedure longer (and frustrating). Add one diode to "isolate" TPS3705 reset pin from Ardino Due RESET line.

**Comment by prasimix** [comment]
Fixed

**Comment by algaremi** [comment]
Do you have a schematic for this mod? I would like to add it to my Arduino shield. Thanks
SB

**Comment by prasimix** [comment]
This one is not trivial, it require that IC32 is removed that one trace beneath it can be cut. Also one 0.8 mm hole has to be drilled on the right position. Use any THT signal diode e.g. 1N4148:

![r3b4 reset correction](https://cloud.githubusercontent.com/assets/15106476/21130857/6ffae1b8-c10b-11e6-940f-5b43b8c2d4d3.JPG)

![r3b4 reset correction 2](https://cloud.githubusercontent.com/assets/15106476/21130873/8f717282-c10b-11e6-8fee-5fba3f5fd873.JPG)

![r3b4 reset correction 3](https://cloud.githubusercontent.com/assets/15106476/21130884/9780e002-c10b-11e6-8f5a-378f17e075d1.png)

That correction is applicable to Arduino Shield r3B4 (from PCB panel r5B9).

**Comment by bgat** [comment]
Why not just lift pin 7 on IC32?

**Comment by prasimix** [comment]
Good point, thanks! :+1:

**Comment by bgat** [comment]
And is the via near the "2" in "IC32" connected to pin 3? If so, maybe you could solder the diode to that rather than drilling a hole...

**Comment by bgat** [comment]
Wait, nevermind... 😂

**Comment by bgat** [comment]
Wait, I take that back...once you lift pin 7, and just looking at the pics (and not schematics, which I don't have in front of me), it appears you might have a couple of vias you could solder the diode to. So maybe the pass-thru hole isn't necessary.

I belabor the point only because drilling is irreversible, and if a noob (like me when I'm under caffeinated) makes that kind of mistake, suddenly they're into a much bigger problem...

**Comment by prasimix** [comment]
I understand that. If you really want to be on the safe side, forgot this hack. Only obstacle is that you need to push reset manually while firmware is uploading.

**Comment by bgat** [comment]
Nope, I want automatic AND safety. Call me lazy, or call me preparing for someone like me who won't read directions. 😂

**Comment by prasimix** [comment]
:) that's also fine. That's why this issue is opened and fixed in the recent revision.
