### ISSUE TITLE
Multiple fixed outputs for digital design

### ISSUE THREAD

**Issue by PurnenduK90** [eez-open/psu-hw#22]
I will suggest some fixed outputs to easily work with digital design. e.g. 5V, 3.3V, 2.5V, 1.25V. As an electronics engineer, I never find one power supply enough for testing purpose, due to multiple voltage levels required in modern designs.

**Comment by prasimix** [comment]
Please open one issue per suggestion in the future.

**Comment by prasimix** [comment]
For multiple outputs we should in the future replace existing AC/DC converters (2 x 48V, 1 x 12V) with one **open source** LLC converter ([example](https://github.com/yu3ma/FSFR2100_LLC_SMPS)) with multiple isolated outputs. 
Another possibility is to go with "rackable" design with backplane that can grow to at least 8 different test&measurements modules with central TFT console.

**Comment by prasimix** [comment]
For multiple outputs check [EEZ BB3](https://github.com/eez-open/modular-psu) project.
