### ISSUE TITLE
possible spike when switching sense relay

### ISSUE THREAD

**Issue by faultylee** [eez-open/psu-hw#27]
Hi guys, great job on the PSU design, and also making this open source. 

Btw, I noticed that there's could possibly be voltage spike when switching sense relay on and off. Also, when the remote sense input is disconnected accidentally or when the relay fail, how much will the output voltage be restricted?

**Comment by prasimix** [comment]
Thanks for your input. R32, R57 (see [Sheet 3 of 12](https://raw.githubusercontent.com/eez-open/psu-hw/master/Consolidated/EEZ%20PSU%20consolidated%20r5B12%20Sheet%203of12.png)) is a guard against entering remote sensing when remote sense inputs are not connected with the power outputs. 
Another guard is remote polarity detection accomplished with Q18, Q20 (see [Sheet 5 of 12](https://raw.githubusercontent.com/eez-open/psu-hw/master/Consolidated/EEZ%20PSU%20consolidated%20r5B12%20Sheet%205of12.png)) when wiring is wrong or insufficient (i.e. only one input is connected to the power output).

**Comment by faultylee** [comment]
:+1:
