### ISSUE TITLE
Where can I find the complete schematic diagrams?

### ISSUE THREAD

**Issue by dagema** [eez-open/psu-hw#29]
I have looked through all repositories, but am unable to find any detailed schematic diagrams. Does that not belong included in open HW design?  Where can I find it? I am not interested in BOM or board layouts, only the schematics.

**Comment by prasimix** [comment]
All schematic is available in three formats: [Eagle](https://github.com/eez-open/psu-hw/blob/master/Consolidated/Eagle%20files/EEZ%20PSU%20consolidated%20r5B12.sch), [bitmaps](https://github.com/eez-open/psu-hw/tree/master/Consolidated) and [pdf](https://github.com/eez-open/psu-hw/blob/master/Consolidated/EEZ%20PSU%20consolidated%20r5B12.pdf). Information about that can be find also on the "home page" ([README.md](https://github.com/eez-open/psu-hw/blob/master/README.md)) of this repository where you can read:

_Files in this repository are organized using the following folders:_
- _Consolidated - contains information about all modules. That include BOM with parts required to build complete dual channel unit (1 x Aux, 2 x Power, and 1 x Arduino Shield). Use this as a primary reference for PCB manufacturing and assembling._
- _Aux power - information about Auxiliary power module only_
- _Power board - information about Power board only_
- _Arduino shield - information about Arduino Shield only_
- _Mechanical - drawings for metal custom enclosure and acrylic demonstration enclosure._
