### ISSUE TITLE
BOM Errors?

### ISSUE THREAD

**Issue by jwilhelm1** [eez-open/psu-hw#35]
R18 on the power boards isn't listed in the BOM
The listed inductor for L1 doesn't fit the board footprint. RN114-4-02-1MS does fit.

**Comment by prasimix** [comment]
R18 is missing, I'm going to add it, but I'm not so sure about L1. It's changed from 1.5mH to 0.7mH that is much smaller but both can be used (it's now smaller due to #25). Please let me know what Power board revision you are referring at?

**Comment by jwilhelm1** [comment]
The power board I am assembling is 02/2017 r5B12.

**Comment by prasimix** [comment]
OK, but r5B12 is still open for revisions and you can see that few builds exists on the GitHub (started from Feb 13th build d9b361a). That will be like that until it become an official new release that will be listed [here](https://github.com/eez-open/psu-hw/releases).  
It's quite possible that you used some of earlier builds and have the following situation:

![power board r5b12 early version](https://cloud.githubusercontent.com/assets/15106476/24297285/89734b80-10a2-11e7-9368-557d17cbaf88.JPG)

As you can see nothing dramatic that you cannot fix on your board too.

**Comment by jwilhelm1** [comment]
Thanks. I'm new to GitHub, so I'm still learning how to navigate it.

**Comment by prasimix** [comment]
No problem, and many thanks for your patience and contribution.
