### ISSUE TITLE
Pin numbering of L1 (RN112-4-02) is wrong. 

### ISSUE THREAD

**Issue by phuebner** [eez-open/psu-hw#38]
I noticed that the pin numbering of the choke L1 on the power board is not matching the datasheet.
[Datasheet RN112-4-02](http://www.schaffner.com/fileadmin/media/products/pim/DS_RNseries_20110616_web18.pdf)
<img src="https://cloud.githubusercontent.com/assets/4952144/24693309/2f13ab1e-19dd-11e7-8aa9-0372b9713afa.png" width="400">
<img src="https://cloud.githubusercontent.com/assets/4952144/24693327/4ab29d12-19dd-11e7-8081-75e5b91db32a.png" width="400">

**Comment by prasimix** [comment]
Fixed
