### ISSUE TITLE
AC power switch failure and TR1 +12V rail failure

### ISSUE THREAD

**Issue by madscientist159** [eez-open/psu-hw#47]
Received kit today, set both internal PSUs to 115V (local US voltage), assembled it, eagerly plugged it in and ... nothing.  No lights, no fan, nothing.

Double checked all wiring already; will start debugging shortly.  Has anyone else experienced this?  Note that on my unit the rear power switch did not easily go into the "On" position; I don't know if I may have received a unit with a defective rear power switch?

**Comment by madscientist159** [comment]
And in case anyone asks, yes, the fuse tray is installed with both fuses :wink:

**Comment by madscientist159** [comment]
And the verdict is...defective mains switch :nauseated_face:   One pole doesn't close in the "On" position.

Can I just get a replacement switch sent out?

**Comment by madscientist159** [comment]
Starting to wonder if you guys shipped a defective rear panel.  With mains switch bypassed unit enters boot loop; seems like main PSU can't supply enough power to keep front panel / control electronics engaged.  Unit tries to start up, runs out of stored energy in PSU caps, then resets and tries to start up again.

Not exactly a happy camper here. :-1:

**Comment by madscientist159** [comment]
Uplugging fan fixed startup issues but...no fan means unit is unable to be installed on bench.  This rear panel assembly seems to be quite messed up; can you overnight a new one?

EDIT: Fan works on 9V source.  Guessing the switching power supply on the AUX board is not working.  Again, this looks like a defective panel was shipped instead of a functional panel.  Were these individually tested or just tested via random sampling?

Would prefer that you just overnight a replacement panel since this is a fairly serious defect.

**Comment by prasimix** [comment]
Hi, as mentioned in the _[kit assembly instructions](http://www.envox.hr/eez/bench-power-supply/group-buy-kit-assembly.html)_ PCB modules are tested independently of accompanying parts therefore AUX power module board is tested without all parts mounted on the rear panel. But, all parts are genuine and installed as received from the distributor (e.g. TME in case of main switch). It's possible that main switch is ruined while wires are inserted in it. But, that cannot explain why AUX power module doesn't work. Please first check without any load if you can get +5 V and +12 V on TR1 outputs.

**Comment by madscientist159** [comment]
Interesting that you mention that.  Just checked under load and the "12V" output reads 17V (!) while the 5V output is a stable 4.95V.

FWIW I am an electrical engineer with many, many years experience with systems that are more complex than this one.  The switch problem I can sort of understand, what I don't understand is how this unit passed testing with a faulty standby regulator module.

EDIT: I'm slowly going through the schematics to see if anything external could be causing this issue, but really that regulator seems to be a self contained unit.  It's somewhat disconcerting that it failed in such a way as to dump 17V across a 12V rail; this may have caused follow-on damage to the fan controller but I have not had a chance to test this yet.

EDIT2: Just so that we're talking about the same nodes here...

12V rail measured at C77 pads
5V rail measured at C80 pads

**Comment by madscientist159** [comment]
@prasimix Any idea of when I can get a replacement for the failed module?  We have rework facilities here so if it will be faster to just send out a switch module and a replacement VTX-214-005-0512 I'm OK with that.

**Comment by prasimix** [comment]
If I understand you correctly TR1 +12 V rail is defective. But, even if that is a case, with proper +5 V rail your unit should start and power up self-test will report fan error. Please let me know what you get in you case.

**Comment by madscientist159** [comment]
@prasimix That is exactly what happens.  However, I don't want to run the unit w/o a fan for any significant period of time since the two power supply boards contain linear regulators and I get concerned about overall heat dissipation.

**Comment by prasimix** [comment]
Ok, overheating cannot happen since firmware when detecting fan error limit max. output current to 2 A (defined by `ERR_MAX_CURRENT` constant).

**Comment by madscientist159** [comment]
@prasimix Good to know.  Still, I purchased a kit that was supposed to contain fully functional PCBs, and I need more than 2A on the outputs.  How soon can I get replacements for the two defective components?

**Comment by prasimix** [comment]
I cannot answer in this moment how soon you can get replacement. Please note that we are not factory, and that this campaign was actually a group buy. Therefore no extra boards nor service parts are available. I have to order it, and that will take time. Also I cannot initiate a new order as someone report a problem, but I have to combine parts from more incidents (if that will happen) to save shipping costs.

**Comment by madscientist159** [comment]
@prasimix All right then, how about a partial refund and I'll just source the parts?

**Comment by prasimix** [comment]
That's also possible, I have to discuss that with Crowd Supply first. Give me a day or two.

**Comment by madscientist159** [comment]
@prasimix OK, thanks! :smile:

**Comment by prasimix** [comment]
Please send me your PayPal email using contact [form](http://www.envox.hr/eez/contact-us.html).

**Comment by madscientist159** [comment]
@prasimix Email sent.

**Comment by madscientist159** [comment]
Need to add one more defect to the list...this power board was a mess.  In addition to everything else (causing the module failure?) the fan power leads were swapped inside the fan connector!  Replacing the module and manually flipping the red / black wires appears to have restored the rear panel to operation, a couple of weeks late and with a $20 extra investment in replacement parts.

Overall not happy here...won't order again or recommend until the rear panel gets better QA.
