### ISSUE TITLE
Grammar fixes for Assembly instructions

### ISSUE THREAD

**Issue by Cabalist** [eez-open/psu-hw#48]
Hey there!  Got My Crowd Supply kit yesterday and just finished assembling it.  I'd like to suggest some clarifications and grammar for the assembly instructions.  Are they located on github?

**Comment by prasimix** [comment]
Sure, it's [here](https://github.com/eez-open/psu-hw/blob/master/Building%20instructions/Complete%20kit%20assembly%20instructions.odt).

**Comment by szwesleyzhao** [comment]
so cool

**Comment by prasimix** [comment]
Nothing happened, closed.
