### ISSUE TITLE
Power board self-test fail on newly assembled H24005

### ISSUE THREAD

**Issue by amuir2k** [eez-open/psu-hw#51]
Folks,

I just built up my fulfillment kit for the H24005, very well designed and executed - unfortunately - I'm getting a self-test error that IOEXP and ADC are failing on both channels.  I've updated to the latest FW, but this did not help.  All cables appear in good shape and in correct orientation.

Where to start to troubleshoot this?

Thanks,

Art

**Comment by prasimix** [comment]
1. Check if Power board have +48 V on its input (X1)
2. Check bias voltages on ferrite beads FB1 (+5 V), FB2 (+5 V) and FB3 (-5 V)

**Comment by amuir2k** [comment]
Thanks, that solved it, I hadn't switched the supplies off of the 230V
input setting (Doh!)
