### ISSUE TITLE
Typos in power board description

### ISSUE THREAD

**Issue by Erik-k** [eez-open/psu-hw#55]
(Hope this is the right place to put this) In the description of the power board at http://www.envox.hr/eez/bench-power-supply/power-board.html there are several typos or suspected typos. Entirely possible it's my own ignorance too in which case I'd love to learn. 

First: in "Bias Power Supply" section, third paragraph, since the \ERROR signal is active-low, the sentence "The MCU will not enable power output during start up until that signal is low." sounds wrong and I think it should be "will not enable power until that signal is **high**" which means there is no error. 

Second: "Series/Pass element and control loops" section, third paragraph, the description of how Q4 works doesn't make sense to me and I asked a very experienced analog engineer about it too. Both of us think that the paragraph should be talking about the Vgs not Vgd. Why does the gate need to be so much higher than the drain on an N-FET? Vgs certainly, and the paragraph makes sense if "drain" is replaced with "source". Vgs needs to be positive and ~5V higher gate than source to keep the FET on.

**Comment by prasimix** [comment]
First: this is correct, is should be "**while** this signal is low" or as you suggested "until that signal is **high**"

Second: maybe we should use here needed relation between Vgs and Vds for Q4 as source follower?
