### ISSUE TITLE
Consider presenting at FOSDEM in 2018

### ISSUE THREAD

**Issue by kasbah** [eez-open/psu-hw#61]
I am very impressed with your project, great job on the documentation! I  thought would let you know that there will be an Open Hardware dev room at FOSDEM next year. Call for participation is available, with links, at https://www.ohwr.org/projects/ohr-meta/wiki/FOSDEM2018

> This is the call for participation in the FOSDEM 2018 devroom on
> Computer Aided Design (CAD) tools and Open Hardware, to be held on
> Saturday 3 February 2018 in Brussels, Belgium. We are looking for
> contributions under the form of talks and tutorials covering the
> following main topics:
>
> - Printed Circuit Board (PCB) design tools (e.g. KiCad and gEDA)
>
> - Analogue and digital simulators (e.g. ngspice, Qucs, Gnucap, Xyce,
> GHDL, Icarus and Verilator)
>
> - Any other EDA tools such as high-level tools for digital hardware
> design (e.g. Migen) and HDL synthesis tools (e.g. Yosys)
>
> - Field solvers such as openEMS
>
> - Mechanical 2D and 3D CAD tools such as LibreCAD, FreeCAD, OpenSCAD and
> SolveSpace
>
> - Open Hardware projects such as the Teres laptop and the lowRISC SoC
>
> - Inter-project opportunities for collaboration
>
> We hope to provide an opportunity for attendees to bring themselves up
> to date on the latest FOSS CAD and Open Hardware developments, share
> knowledge and identify opportunities to collaborate on development
> tasks. This devroom is an evolution of the EDA devroom we organised in
> 2015, 2016 and 2017.

**Comment by prasimix** [comment]
Hi, and thanks for information about FOSDEM. Please note that GitHub issue tracker is not a place for such promotion. You can use our [contact form](http://www.envox.hr/eez/contact-us.html) in the future.
